<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <PlatformTarget Condition="'$(Platform)' == 'x86'">x86</PlatformTarget>
    <PlatformTarget Condition="'$(Platform)' == 'x64'">x64</PlatformTarget>
  </PropertyGroup>
</Project>
