import Foundation

struct TinifyCompressor: ImageCompressor, Sendable {
    private static let shrinkURL = URL(string: "https://api.tinify.com/shrink")!
    // Generated by macOS ImageIO and accepted by Tinify's decoder. A smaller
    // synthetic PNG was readable by macOS but rejected by Tinify as malformed.
    private static let validationPNG = Data(base64Encoded: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAGJlWElmTU0AKgAAAAgAAgExAAIAAAARAAAAJodpAAQAAAABAAAAOAAAAABBZG9iZSBJbWFnZVJlYWR5AAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAAaADAAQAAAABAAAAAQAAAAAZGel9AAABZGlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNi4wLjAiPgogICA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPgogICAgICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgICAgICAgICB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iPgogICAgICAgICA8eG1wOkNyZWF0b3JUb29sPkFkb2JlIEltYWdlUmVhZHk8L3htcDpDcmVhdG9yVG9vbD4KICAgICAgPC9yZGY6RGVzY3JpcHRpb24+CiAgIDwvcmRmOlJERj4KPC94OnhtcG1ldGE+CgQ+9BsAAAANSURBVAgdY/BfcKcFAAVdAlCKpBDmAAAAAElFTkSuQmCC")!

    private let apiKey: String
    private let session: URLSession

    init(apiKey: String, session: URLSession = .shared) {
        self.apiKey = apiKey
        self.session = session
    }

    /// Tinify has no free account-validation endpoint. This sends a 1×1 PNG,
    /// which validates credentials but consumes one normal compression quota.
    func validateAPIKey() async throws {
        _ = try await shrink(uploadData: Self.validationPNG)
    }

    func compress(
        source: URL,
        temporaryDestination: URL,
        progress: @escaping @Sendable (Double) -> Void
    ) async throws {
        progress(0)

        let sourceData: Data
        do {
            sourceData = try Data(contentsOf: source)
        } catch {
            throw CompressionFailure.localExecution("Unable to read the source image.")
        }

        let outputURL = try await shrink(uploadData: sourceData)
        progress(0.5)

        let outputData = try await download(from: outputURL)
        guard !outputData.isEmpty else {
            throw CompressionFailure.outputValidation("Tinify returned an empty output file.")
        }

        do {
            try outputData.write(to: temporaryDestination, options: .atomic)
        } catch {
            throw CompressionFailure.outputValidation("Unable to write Tinify output.")
        }
        progress(1)
    }

    private func shrink(uploadData: Data) async throws -> URL {
        var request = URLRequest(url: Self.shrinkURL)
        request.httpMethod = "POST"
        request.httpBody = uploadData
        request.setValue("image/png", forHTTPHeaderField: "Content-Type")
        authorize(&request)

        let (data, response) = try await perform(request)
        try validate(response: response, data: data)

        let decoded: ShrinkResponse
        do {
            decoded = try JSONDecoder().decode(ShrinkResponse.self, from: data)
        } catch {
            throw CompressionFailure.apiResponse(
                statusCode: response.statusCode,
                message: "Tinify response is malformed."
            )
        }
        guard let outputURL = decoded.output?.url else {
            throw CompressionFailure.apiResponse(
                statusCode: response.statusCode,
                message: "Tinify response is missing output.url."
            )
        }
        guard isTrustedOutputURL(outputURL) else {
            throw CompressionFailure.apiResponse(
                statusCode: response.statusCode,
                message: "Tinify response contains an untrusted output URL."
            )
        }
        return outputURL
    }

    private func download(from outputURL: URL) async throws -> Data {
        var request = URLRequest(url: outputURL)
        request.httpMethod = "GET"

        let redirectDelegate = TrustedOutputRedirectDelegate()
        do {
            let (data, urlResponse) = try await session.data(for: request, delegate: redirectDelegate)
            guard let response = urlResponse as? HTTPURLResponse else {
                throw CompressionFailure.transport("Tinify returned an invalid network response.")
            }
            try validate(response: response, data: data)
            return data
        } catch let failure as CompressionFailure {
            throw failure
        } catch {
            if let rejectedStatusCode = redirectDelegate.rejectedStatusCode {
                throw CompressionFailure.apiResponse(
                    statusCode: rejectedStatusCode,
                    message: "Tinify output download unexpectedly redirected."
                )
            }
            throw CompressionFailure.transport(error.localizedDescription)
        }
    }

    private func authorize(_ request: inout URLRequest) {
        let credentials = Data("api:\(apiKey)".utf8).base64EncodedString()
        request.setValue("Basic \(credentials)", forHTTPHeaderField: "Authorization")
    }

    private func isTrustedOutputURL(_ url: URL) -> Bool {
        Self.isTrustedOutputURL(url)
    }

    private static func isTrustedOutputURL(_ url: URL) -> Bool {
        url.scheme == "https" && url.host == "api.tinify.com" && url.path.hasPrefix("/output/")
    }

    private func perform(_ request: URLRequest) async throws -> (Data, HTTPURLResponse) {
        do {
            let (data, response) = try await session.data(for: request)
            guard let response = response as? HTTPURLResponse else {
                throw CompressionFailure.transport("Tinify returned an invalid network response.")
            }
            return (data, response)
        } catch let failure as CompressionFailure {
            throw failure
        } catch {
            throw CompressionFailure.transport(error.localizedDescription)
        }
    }

    private func validate(response: HTTPURLResponse, data: Data) throws {
        guard (200 ... 299).contains(response.statusCode) else {
            switch response.statusCode {
            case 401:
                throw CompressionFailure.invalidAPIKey
            case 429:
                throw CompressionFailure.quotaExceeded
            default:
                throw CompressionFailure.apiResponse(
                    statusCode: response.statusCode,
                    message: errorMessage(from: data)
                )
            }
        }
    }

    private func errorMessage(from data: Data) -> String? {
        try? JSONDecoder().decode(TinifyErrorResponse.self, from: data).message
    }
}

private struct ShrinkResponse: Decodable {
    struct Output: Decodable {
        let url: URL?
    }

    let output: Output?
}

private struct TinifyErrorResponse: Decodable {
    let message: String?
}

final class TrustedOutputRedirectDelegate: NSObject, URLSessionTaskDelegate, @unchecked Sendable {
    private let lock = NSLock()
    private var rejectedStatus: Int?

    var rejectedStatusCode: Int? {
        lock.lock()
        defer { lock.unlock() }
        return rejectedStatus
    }

    func urlSession(
        _ session: URLSession,
        task: URLSessionTask,
        willPerformHTTPRedirection response: HTTPURLResponse,
        newRequest request: URLRequest,
        completionHandler: @escaping (URLRequest?) -> Void
    ) {
        lock.lock()
        rejectedStatus = response.statusCode
        lock.unlock()
        completionHandler(nil)
    }
}
