<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>PngCut</AssemblyName>
    <RootNamespace>PngCut.Desktop</RootNamespace>
    <ApplicationIcon>Resources\AppIcon.ico</ApplicationIcon>
    <PlatformTarget Condition="'$(Platform)' == 'x86'">x86</PlatformTarget>
    <PlatformTarget Condition="'$(Platform)' == 'x64'">x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PngCut.Core\PngCut.Core.csproj" />
    <ProjectReference Include="..\PngCut.Engine\PngCut.Engine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\AppIcon.ico" />
    <Content Include="Resources\engines\**\*.exe" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Resources\licenses\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
